"""init_schema

Revision ID: 2fd6424ff999
Revises: 
Create Date: 2026-08-30 17:42:47.466980
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '2fd6424ff999'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learner_profiles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('ai_recommendations', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learner_profiles_email'), 'learner_profiles', ['email'], unique=True)
    op.create_index(op.f('ix_learner_profiles_username'), 'learner_profiles', ['username'], unique=True)
    op.create_table('sim_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('learner_id', sa.String(), nullable=True),
    sa.Column('scenario_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('turn_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['learner_id'], ['learner_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sim_sessions_learner_id'), 'sim_sessions', ['learner_id'], unique=False)
    op.create_table('interaction_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('turn_no', sa.Integer(), nullable=True),
    sa.Column('user_message', sa.Text(), nullable=True),
    sa.Column('patient_dialogue', sa.Text(), nullable=True),
    sa.Column('system_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sim_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interaction_logs_session_id'), 'interaction_logs', ['session_id'], unique=False)
    op.create_table('report_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('status_badge', sa.String(), nullable=True),
    sa.Column('correct_actions', sa.Integer(), nullable=True),
    sa.Column('incorrect_actions', sa.Integer(), nullable=True),
    sa.Column('reaction_score', sa.Integer(), nullable=True),
    sa.Column('criteria_json', sa.Text(), nullable=True),
    sa.Column('strengths', sa.Text(), nullable=True),
    sa.Column('errors', sa.Text(), nullable=True),
    sa.Column('suggestions', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sim_sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_table('vital_states',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('heart_rate', sa.Integer(), nullable=True),
    sa.Column('blood_pressure', sa.String(), nullable=True),
    sa.Column('spo2', sa.Integer(), nullable=True),
    sa.Column('consciousness', sa.String(), nullable=True),
    sa.Column('turn_no', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sim_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vital_states_session_id'), 'vital_states', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vital_states_session_id'), table_name='vital_states')
    op.drop_table('vital_states')
    op.drop_table('report_results')
    op.drop_index(op.f('ix_interaction_logs_session_id'), table_name='interaction_logs')
    op.drop_table('interaction_logs')
    op.drop_index(op.f('ix_sim_sessions_learner_id'), table_name='sim_sessions')
    op.drop_table('sim_sessions')
    op.drop_index(op.f('ix_learner_profiles_username'), table_name='learner_profiles')
    op.drop_index(op.f('ix_learner_profiles_email'), table_name='learner_profiles')
    op.drop_table('learner_profiles')
    # ### end Alembic commands ###
