"""upgrade

Revision ID: 43aabff78614
Revises: d9381706381d
Create Date: 2026-08-29 11:59:36.836057
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '43aabff78614'
down_revision: Union[str, None] = 'd9381706381d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('learner_profiles', 'training_track')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('learner_profiles', sa.Column('training_track', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
