"""upgrade

Revision ID: d9381706381d
Revises: 31183d6f350d
Create Date: 2026-08-29 11:17:56.487783
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd9381706381d'
down_revision: Union[str, None] = '31183d6f350d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('learner_profiles', sa.Column('email', sa.String(), nullable=True))
    op.add_column('learner_profiles', sa.Column('password_hash', sa.String(), nullable=True))
    op.create_index(op.f('ix_learner_profiles_email'), 'learner_profiles', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_learner_profiles_email'), table_name='learner_profiles')
    op.drop_column('learner_profiles', 'password_hash')
    op.drop_column('learner_profiles', 'email')
    # ### end Alembic commands ###
